### ISSUE TITLE
silk -a spin handles auto spin but we no longer get the auto browser refresh

### ISSUE THREAD

**Issue by rossputin** [silk-web-toolkit/silk#94]
pretty sure we used to hook up a browser reload so we would see the change occurring as we make it

**Comment by Shnick** [comment]
Its working for me .. maybe its fixed as a side effect of some of the other changes I've made. Can you try with the latest silk and gui?

To build the gui
./build.sh update && ./run.sh 

Oh I had issues with running silk with drip - wasn't killing process and the reload feature broke.

**Comment by rossputin** [comment]
I didn't know you had finished updating the GUI :-)

**Comment by Shnick** [comment]
I haven't mate ... just played round with the style :-)

I'd like to allow config of edn structure and might retry our clojure script port. 

Are you up and running ok now ?

**Comment by rossputin** [comment]
There is no rush thanks Nick.  We can have a look over a curry next week :-)

**Comment by rossputin** [comment]
Think this was done via bash script... for CLI also back in the day. Is this worth resurrecting ?

**Comment by Shnick** [comment]
Nope
